/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digisigninform;

import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author kraft
 */
public class SignInFront extends javax.swing.JFrame {

    /**
     * Creates new form SignInFront
     */
    public SignInFront() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        contactText = new javax.swing.JScrollPane();
        conactInfo = new javax.swing.JTextArea();
        workOrderText = new javax.swing.JScrollPane();
        woTextArea = new javax.swing.JTextArea();
        fNameText = new javax.swing.JTextField();
        fnameLabel = new javax.swing.JLabel();
        lNameText = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneOneText = new javax.swing.JTextField();
        cellLabel = new javax.swing.JLabel();
        cellPhoneText = new javax.swing.JTextField();
        equipService = new javax.swing.JLabel();
        equipmentField = new javax.swing.JScrollPane();
        equipmentText = new javax.swing.JTextArea();
        workToDoText = new javax.swing.JLabel();
        workToDoField = new javax.swing.JScrollPane();
        workToBeDone = new javax.swing.JTextArea();
        checkLaptop = new javax.swing.JCheckBox();
        checkDesktop = new javax.swing.JCheckBox();
        checkTablet = new javax.swing.JCheckBox();
        passLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        pinLabel = new javax.swing.JLabel();
        pinText = new javax.swing.JTextField();
        techLabel = new javax.swing.JLabel();
        techComboBox = new javax.swing.JComboBox<>();
        emailLabel = new javax.swing.JLabel();
        eMailText = new javax.swing.JTextField();
        checkCharger = new javax.swing.JCheckBox();
        workPerformedLabel = new javax.swing.JLabel();
        workPerformedArea = new javax.swing.JScrollPane();
        workDoneText = new javax.swing.JTextArea();
        partsUsedLabel = new javax.swing.JLabel();
        partBox = new javax.swing.JTextField();
        minChargeLabel = new javax.swing.JLabel();
        MinChargeText = new javax.swing.JTextField();
        legalPane = new javax.swing.JScrollPane();
        legalText = new javax.swing.JTextArea();
        SigLabel = new javax.swing.JLabel();
        signText = new javax.swing.JTextField();
        commitButt = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        searchButt = new javax.swing.JButton();
        printButt = new javax.swing.JButton();
        connectedText = new javax.swing.JLabel();
        clientIDText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Service Work Order");

        contactText.setBorder(null);
        contactText.setFocusable(false);

        conactInfo.setEditable(false);
        conactInfo.setColumns(20);
        conactInfo.setRows(3);
        conactInfo.setText("102-1980 Cooper Rd., Kelowna, B.C., Canada V1Y-8K5\nPhone: 250-868-9765 / 250-763-2492 | Fax:877-263-8594\nwww.ncro.ca | service@ncro.ca | facebook.com/ncrodotca");
        conactInfo.setAutoscrolls(false);
        conactInfo.setBorder(null);
        contactText.setViewportView(conactInfo);

        workOrderText.setBorder(null);

        woTextArea.setColumns(5);
        woTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        woTextArea.setRows(2);
        woTextArea.setText("Work Order ID");
        woTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        workOrderText.setViewportView(woTextArea);

        fnameLabel.setText("First Name:");

        phoneLabel.setText("Phone:");

        cellLabel.setText("Cell:");

        equipService.setText("Equipment to be serviced:");

        equipmentText.setColumns(20);
        equipmentText.setRows(4);
        equipmentField.setViewportView(equipmentText);

        workToDoText.setText("Work to be Done:");

        workToBeDone.setColumns(20);
        workToBeDone.setLineWrap(true);
        workToBeDone.setRows(5);
        workToBeDone.setWrapStyleWord(true);
        workToDoField.setViewportView(workToBeDone);

        checkLaptop.setBackground(new java.awt.Color(255, 255, 255));
        checkLaptop.setText("Laptop");
        checkLaptop.setBorder(null);
        checkLaptop.setOpaque(true);

        checkDesktop.setBackground(new java.awt.Color(255, 255, 255));
        checkDesktop.setText("Desktop");

        checkTablet.setBackground(new java.awt.Color(255, 255, 255));
        checkTablet.setText("Tablet");

        passLabel.setText("Password:");

        pinLabel.setText("Pin:");

        techLabel.setText("Tech:");

        techComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Chris Reid", "Zane Zieske", "Dillan Timpany", "Tyson Schlehahn" }));

        emailLabel.setText("E-Mail:");

        checkCharger.setBackground(new java.awt.Color(255, 255, 255));
        checkCharger.setText("Charger");

        workPerformedLabel.setText("Work Performed:");

        workPerformedArea.setBorder(null);

        workDoneText.setColumns(20);
        workDoneText.setLineWrap(true);
        workDoneText.setRows(5);
        workDoneText.setWrapStyleWord(true);
        workDoneText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        workPerformedArea.setViewportView(workDoneText);

        partsUsedLabel.setText("Parts Used:");

        partBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        minChargeLabel.setText("Minimum Charge:");

        MinChargeText.setText("$50");

        legalPane.setBorder(null);

        legalText.setEditable(false);
        legalText.setColumns(20);
        legalText.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        legalText.setLineWrap(true);
        legalText.setRows(5);
        legalText.setText("I agree to release the above equipment to National Computer Resource (\"NCR\") for evaluation and/or repair. I agree that NCr is in no way responsible for the condition of equipment prior to be serviced, or for lost or damaged data that may occur during the evaluation and/or repair. I agree that the above description of the equipment is based solely upon my representations and may be in error. I agree that NCR makes no representations, warranties or guarantees as to the lenfth of time to make an evaluation or repair, as to whether can in fact be made, or as to the current or future impact any evaluation or repairs may have on existing hardware, software or external and peripheral devices that may be attached to the equipment (eg., networks). I agree that service fees are payable whether or not a problem is solved. I agree that National Computer Resource will not release the above equipment until all parts and/or labour charges have been paid in full. I agree that after 90-days all unclaimed equipment becomes property of NCR.");
        legalText.setWrapStyleWord(true);
        legalText.setBorder(null);
        legalText.setFocusable(false);
        legalText.setOpaque(false);
        legalPane.setViewportView(legalText);

        SigLabel.setText("Client SIgnature:");

        signText.setEditable(false);
        signText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signText.setText("________________________________________________________________________________________________________________");
        signText.setAutoscrolls(false);
        signText.setBorder(null);
        signText.setFocusable(false);
        signText.setHighlighter(null);
        signText.setOpaque(true);

        commitButt.setText("Save");
        commitButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtActionPerformed(evt);
            }
        });

        lastNameLabel.setText("Last Name:");

        searchButt.setText("Search");
        searchButt.setFocusPainted(false);
        searchButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtActionPerformed(evt);
            }
        });

        printButt.setText("Print");
        printButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtActionPerformed(evt);
            }
        });

        connectedText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        connectedText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legalPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cellLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fnameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(phoneOneText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                            .addComponent(cellPhoneText))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lNameText)
                                        .addGap(12, 12, 12)))
                                .addComponent(equipmentField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equipService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(workToDoText, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkCharger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(workToDoField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(pinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(techLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordText)
                            .addComponent(pinText)
                            .addComponent(techComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eMailText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(workPerformedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partsUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SigLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signText, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workPerformedArea, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(minChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MinChargeText, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partBox)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(commitButt)
                                .addGap(18, 18, 18)
                                .addComponent(printButt)
                                .addGap(23, 23, 23))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchButt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(connectedText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientIDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(workOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(connectedText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clientIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButt)))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipService, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneOneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(equipmentField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workToDoText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCharger, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workToDoField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(techLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(techComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workPerformedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partsUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(partBox)
                    .addComponent(workPerformedArea, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinChargeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commitButt)
                    .addComponent(printButt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(legalPane, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commitButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitButtActionPerformed

        String connectionUrl
                = "jdbc:sqlserver://sql.kraftytek.ca:1433;"
                + "encrypt=false;"
                + "databaseName=NCRO_WorkOrders;"
                + "user=sa;"
                + "password=S!lver88";

        try ( Connection connection = DriverManager.getConnection(connectionUrl);  Statement addWorkOrder = connection.createStatement();) {

            //need to add password and pin save and tech
            String currentClient = clientIDText.getText();
            String workToDo = workToBeDone.getText();
            boolean desktop = checkDesktop.isSelected();
            boolean laptop = checkLaptop.isSelected();
            boolean tablet = checkTablet.isSelected();
            boolean charger = checkCharger.isSelected();
            String clientPass = passwordText.getText();
            String clientPin = pinText.getText();
            String techName = techComboBox.getSelectedItem().toString();

            int desktopBool = (desktop) ? 1 : 0;
            int laptopBool = (laptop) ? 1 : 0;
            int tabletBool = (tablet) ? 1 : 0;
            int chargerBool = (charger) ? 1 : 0;

            String addClientScript = "insert into client_service(client_id, work_to_do, pc_pass, pc_pin, tech_name, desktop, laptop, tablet, charger)"
                    + "select " + currentClient + " as client_id,"
                    + "'" + workToDo + "' as work_to_do,"
                    + "'" + clientPass + "' as pc_pass,"
                    + "'" + clientPin + "' as pc_pin,"
                    + "'" + techName + "' as tech_name,"
                    + desktopBool + " as desktop,"
                    + laptopBool + " as laptop,"
                    + tabletBool + " as tablet,"
                    + chargerBool + " as charger";

            System.out.println(addClientScript);

            addWorkOrder.executeUpdate(addClientScript);

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_commitButtActionPerformed

    private void searchButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtActionPerformed
        //open search form
        searchForm gui = new searchForm();
        gui.setVisible(true);

    }//GEN-LAST:event_searchButtActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //generate a new work order number when form is opened, gets max from db + 1  
        String connectionUrl
                = "jdbc:sqlserver://sql.kraftytek.ca:1433;"
                + "encrypt=false;"
                + "databaseName=NCRO_WorkOrders;"
                + "user=sa;"
                + "password=S!lver88";

        try ( Connection connection = DriverManager.getConnection(connectionUrl);  Statement statement = connection.createStatement();) {

            String topWorkOrder = """
                                  select max(work_Order_ID) + 1 as word_order_id
                                  from client_service
                                  """;

            ResultSet searchWO = statement.executeQuery(topWorkOrder);

            while (searchWO.next()) {

                String woText = searchWO.getString(1);
                SignInFront.woTextArea.setText(" Work Order ID: \n            " + woText);
                fNameText.requestFocus();
            }

        } catch (SQLException e) {
        }

        String connectionUrl2
                = "jdbc:sqlserver://sql.kraftytek.ca:1433;"
                + "encrypt=false;"
                + "databaseName=NCRO_WorkOrders;"
                + "user=sa;"
                + "password=S!lver88";

        try ( Connection connection = DriverManager.getConnection(connectionUrl2);  Statement statement = connection.createStatement();) {

            String selectUser = "select username from users where username = 'Connected'";

            ResultSet uNQuery = statement.executeQuery(selectUser);

            // Print results from select statement
            while (uNQuery.next()) {

                connectedText.setText("Connected");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void printButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtActionPerformed

        // TODO add your handling code here:
        Toolkit tkp = jPanel1.getToolkit();
        PrintJob pjp = tkp.getPrintJob(this, null, null);
        Graphics g = pjp.getGraphics();
        jPanel1.print(g);
        g.dispose();
        pjp.end();
    }//GEN-LAST:event_printButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MinChargeText;
    private javax.swing.JLabel SigLabel;
    private javax.swing.JLabel cellLabel;
    public static javax.swing.JTextField cellPhoneText;
    private javax.swing.JCheckBox checkCharger;
    private javax.swing.JCheckBox checkDesktop;
    private javax.swing.JCheckBox checkLaptop;
    private javax.swing.JCheckBox checkTablet;
    public static javax.swing.JLabel clientIDText;
    private javax.swing.JButton commitButt;
    private javax.swing.JTextArea conactInfo;
    private javax.swing.JLabel connectedText;
    private javax.swing.JScrollPane contactText;
    public static javax.swing.JTextField eMailText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel equipService;
    private javax.swing.JScrollPane equipmentField;
    private javax.swing.JTextArea equipmentText;
    public static javax.swing.JTextField fNameText;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField lNameText;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JScrollPane legalPane;
    private javax.swing.JTextArea legalText;
    private javax.swing.JLabel minChargeLabel;
    private javax.swing.JTextField partBox;
    private javax.swing.JLabel partsUsedLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel phoneLabel;
    public static javax.swing.JTextField phoneOneText;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JTextField pinText;
    private javax.swing.JButton printButt;
    private javax.swing.JButton searchButt;
    private javax.swing.JTextField signText;
    private javax.swing.JComboBox<String> techComboBox;
    private javax.swing.JLabel techLabel;
    private javax.swing.JLabel titleText;
    public static javax.swing.JTextArea woTextArea;
    private javax.swing.JTextArea workDoneText;
    private javax.swing.JScrollPane workOrderText;
    private javax.swing.JScrollPane workPerformedArea;
    private javax.swing.JLabel workPerformedLabel;
    private javax.swing.JTextArea workToBeDone;
    private javax.swing.JScrollPane workToDoField;
    private javax.swing.JLabel workToDoText;
    // End of variables declaration//GEN-END:variables
}
